// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-JS4PbhkoxCBUVuxH9yv9CKqgUjPdMt0',
    appId: '1:278024146071:web:753fd5679b235b87306dd2',
    messagingSenderId: '278024146071',
    projectId: 'coba-firebase-api',
    authDomain: 'coba-firebase-api.firebaseapp.com',
    storageBucket: 'coba-firebase-api.appspot.com',
    measurementId: 'G-ZPWE6S4FCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyROBDp8ELAZW0cLeRbnK5Eh1i4v_cgo',
    appId: '1:278024146071:android:e75fb9c8435262a4306dd2',
    messagingSenderId: '278024146071',
    projectId: 'coba-firebase-api',
    storageBucket: 'coba-firebase-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALmeIgrsY3aU1-MNVc-F9fZEbXVyUCeXY',
    appId: '1:278024146071:ios:d0185b7bce5ac30e306dd2',
    messagingSenderId: '278024146071',
    projectId: 'coba-firebase-api',
    storageBucket: 'coba-firebase-api.appspot.com',
    iosBundleId: 'com.example.firebaseApiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALmeIgrsY3aU1-MNVc-F9fZEbXVyUCeXY',
    appId: '1:278024146071:ios:cf35521d3c588405306dd2',
    messagingSenderId: '278024146071',
    projectId: 'coba-firebase-api',
    storageBucket: 'coba-firebase-api.appspot.com',
    iosBundleId: 'com.example.firebaseApiTest.RunnerTests',
  );

// static Future<FirebaseApp> initializeApp() async {
//     return await Firebase.initializeApp(
//       options: DefaultFirebaseOptions.currentPlatform,
//     );
//   }
}
